### ISSUE TITLE
Error: The model gpt-4-preview does not exist

### ISSUE THREAD

**Issue by oersted** [enjalot/latent-scope#18]
When labeling: `ERROR: Error code: 404 - {'error': {'message': 'The model gpt-4-preview does not exist', 'type': 'invalid_request_error', 'param': None, 'code': 'model_not_found'}}`

The model name was deprecated a while ago, now we have either `gpt-4` or `gpt-4-turbo-preview`.

https://platform.openai.com/docs/models/gpt-4-and-gpt-4-turbo

As a quick fix, I locally edited `latenscope/models/chat_models.json` where the package was installed.

**Comment by enjalot** [comment]
this was fixed in https://github.com/enjalot/latent-scope/commit/66ca7ee08659b18f7c7cf3eb1a80f325ed830662
it will be included in a 0.1.1 release soon!
