### ISSUE TITLE
Export data for a scope

### ISSUE THREAD

**Issue by enjalot** [enjalot/latent-scope#32]
Once you have gone through the process and setup a `scope` you may find yourself wanting to use the associated data in another tool or workflow. We should support exporting the data in a couple ways:

1) Easy access to the individual files powering a scope:  
  - input.parquet: original data ingested (may have started as a csv or dataframe) [N, ?]
  - umap.parquet: x,y coordinates from umap [N, 2]
  - embeddings.h5: array of embedding arrays [N, dim]
  - clusters.parquet: cluster_index, raw_cluster_index, [N, 3]
  - cluster_labels.parquet: cluster_index, label, description (lookup table for the labels) [N, 3]
There is also metadata json for each of those files that contains the parameters used to generate them. This could potentially be combined into a single scope.json file?
Alternatively we could combine the parquet files into scope.parquet, leaving only the embeddings separate

2)  Save As [VDF](https://github.com/AI-Northstar-Tech/vector-io)
  - a fileformat for making vector databases portable, so one could easily bring a scope into a supported vector DB
  - we would combine the various files above into a single parquet, essentially adding columns to the original input dataset
  - VDF has a metadata json that keeps track of things like which model was used to embed (and which column was embedded). we could potentially extend it to add metadata on umap parameters and clustering params etc.

## UI considerations
Right now you can see a scope either in Setup or Explore, and we'd likely want to allow you to export from either one. Perhaps it makes sense to have an Export page for a given scope id that can be linked from either. This way we can present various options.

It would be convenient to click to download files, but also we can give paths since in most cases latentscope is running locally.

**Comment by enjalot** [comment]
@arnicas glad you found the files, I definitely intend to document it, as well as make it much easier to download what you're looking at in the UI

**Comment by arnicas** [comment]
It's super - I probably have a few new touches to suggest too, after I finish this demo for tomorrow I'll log them

**Comment by enjalot** [comment]
I've pushed 0.1.6 that includes the export page described in this issue. I decided to start with two things: it creates a combined scope.parquet that has all the steps data together (but not the input data) as well as scope.json which has all the metadata combined.
The page also shows all the files in the dataset, so you could easily download individual pieces if you want.

I've also made it so the save scope always goes through the script. We can update the script to also output a VDF file, which should be fairly straightforward joining of the input.parquet and the scope.parquet (tho we may need to prefix the scope columns with something like `ls_` to not collide with user data. We'd also need to map the metadata to the appropriate format in VDF.

**Comment by enjalot** [comment]
@arnicas how was using the tag indices for you? One thing I'm thinking is how to maybe combine those into a single file for export, or perhaps include them in the scope.parquet (maybe a column per tag?) any thoughts on what a convenient format would be?

**Comment by arnicas** [comment]
Yeah, it would be nice to combine them in some form. A col per tag works? I'll take a look and get back on it.

**Comment by enjalot** [comment]
These ideas have been implemented and released in [0.2.1](https://github.com/enjalot/latent-scope/releases/tag/v0.2.1)
