### ISSUE TITLE
Support configured APIs for embedding and LLM models

### ISSUE THREAD

**Issue by enjalot** [enjalot/latent-scope#35]
Users of the library may want to embed with an existing API (perhaps an internal one). We could allow configuration of "models" that are setup by the user via the UI (Settings page?) and stored in some way (env variables?).

We need to define the necessary variables:
* name
* description
* URL
* API key

We would probably need a "CustomAPI" provider that accepts the user variables and enables submitting requests and returning the responses. How do we add flexibility for parsing responses? 

We would also want the list of models that shows up in dropdowns to show the custom model, likely handled with new code in the models/ lib

**Comment by enjalot** [comment]
If we integrate LiteLLM as discussed in #14 we could look at using:
https://litellm.vercel.app/docs/providers/custom_openai_proxy

**Comment by ishaan-jaff** [comment]
@enjalot I'm the litellm maintainer - let me know if we can help/if you have any feature requests/issues

**Comment by enjalot** [comment]
It would be good to make it easy to utilize llamafile which offers an OpenAI-compatible chat API
https://github.com/Mozilla-Ocho/llamafile/blob/main/README.md#json-api-quickstart

**Comment by enjalot** [comment]
done!
