### ISSUE TITLE
how to install it on a windows machine

### ISSUE THREAD

**Issue by EE2dev** [enjalot/latent-scope#39]
I tried following the instruction to get started but ran into problems with powershell. Does it work on a windows machine?

**Comment by enjalot** [comment]
This is a good question. Unfortunately I don't have access to a windows machine right now.
In general I try to use the python `os` module for all paths so I think it should work? 

Would be great if someone with windows experience can help with instructions here!

**Comment by adhikasp** [comment]
Hi, I can confirm the project works on Windows 11.

Unfortunately I don't document my installation experience. But here is rough step I take to make it works, fwiw:
- [Install Micrososft Visual C++ build tools](https://visualstudio.microsoft.com/visual-cpp-build-tools/), make sure to install this component for few requirement like hdbscan to works
  - Windows 10 SDK
  - MSVC (latest version)
- `pip install latentscope` as per normal instruction

**Comment by enjalot** [comment]
thank you for sharing @adhikasp !
