### ISSUE TITLE
[feature request] Support alternate OpenAI provider URL

### ISSUE THREAD

**Issue by hydrosquall** [enjalot/latent-scope#42]
## Goal

Enable latent-scope to be used with OpenAI Proxy / alternative services that offer OpenAI-compatible endpoints

## Proposal

Users could supply `OPENAI_BASE_URL` in the `.env` file.

I'm willing/able to submit the code & docs change, just wanted to confirm interest/approach first.

**Comment by enjalot** [comment]
that would be great, and we could just default to the normal url.
There was also a discussion in discord about supporting the Azure OpenAI client:
```
import os
from openai import AzureOpenAI

client = AzureOpenAI(
    api_key=os.getenv("AZURE_OPENAI_API_KEY"),
    api_version="2023-12-01-preview",
    azure_endpoint=os.getenv("AZURE_OPENAI_ENDPOINT")
)
```
https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/switching-endpoints

which feels related in that we would be adding a little bit of complexity to the config / openai provider but supporting more API services

**Comment by hydrosquall** [comment]
Configuring the AzureOpenAI client seems like a different feature (given that the entire import is different), but that's a helpful connection to know about.

If the amount of config per model increases beyond having an API key (and includes an api_version, endpoint, etc), it may be worthwhile to switch to a dedicated config file (JSON or YAML) to manage them all.
