### ISSUE TITLE
[bug] Documentation example cells do not load on Safari (Desktop or Mobile)

### ISSUE THREAD

**Issue by hydrosquall** [enjalot/latent-scope#43]
Currently the examples only load in some browsers, like Chrome (haven't tested Firefox). In Safari desktop/mobile, the [example analysis pages](https://enjalot.github.io/latent-scope/datavis-survey) looks like this for the interactive cells

<img width="1238" alt="image" src="https://github.com/enjalot/latent-scope/assets/9020979/7e8f3b5f-e085-4d67-8ee6-70d41e3c8421">

In case adding cross-browser support for the interactive cells is tricky, we could alternately display a fallback banner encouraging users to switch browsers, or display an image instead.

**Comment by hydrosquall** [comment]
Ah - it looks like this missing function only affects older (pre March 2023) versions of Safari on desktop, newer versions should be OK.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/import.meta/resolve

**Comment by enjalot** [comment]
going to close for now since it seems to be an observable framework thing.
