### ISSUE TITLE
Responsive UI for web interface

### ISSUE THREAD

**Issue by enjalot** [enjalot/latent-scope#5]
The layout for the Explore page does not really accommodate smaller screens. It would be good to have the CSS be updated to be responsive to the screen size.

https://github.com/enjalot/latent-scope/blob/main/web/src/pages/Explore.jsx
https://github.com/enjalot/latent-scope/blob/main/web/src/pages/Explore.css

Also sorry for the poor naming conventions. A refactor would help too!

**Comment by AnukratiMehta** [comment]
@enjalot 

Hello, I'd like to work on this.

**Comment by enjalot** [comment]
That would be great! 
There are some [development instructions](https://github.com/enjalot/latent-scope/blob/main/documentation/DEVELOPMENT.md) here but they may not be detailed enough.
Let me know if you have questions getting setup, feel free to join the discord https://discord.gg/tTV4wgVM

**Comment by enjalot** [comment]
Thanks for fixing this @AnukratiMehta !
