### ISSUE TITLE
Text color hard to read in dark mode

### ISSUE THREAD

**Issue by normster** [enjalot/latent-scope#65]
Hi,

This looks like a really neat tool! I'm trying it out on a few of my research datasets but the web UI's text in dark mode is quite hard to read:

<img width="781" alt="image" src="https://github.com/user-attachments/assets/d59c9690-ac4a-4edc-9bbd-6c8bebbc5fb4">

<img width="807" alt="image" src="https://github.com/user-attachments/assets/ee943ff2-ae32-4770-9b7c-ccd3baafa874">

Is there a setting to override dark/light mode for the web UI?

**Comment by enjalot** [comment]
This is definitely something I want to fix soon. I'm working on revamping the UX and will make sure dark mode is consistently supported!

**Comment by enjalot** [comment]
finally done!

**Comment by lambdaofgod** [comment]
I still have the same problem. Checked with version 0.5.2 on Brave and Firefox
