### ISSUE TITLE
Serving issue with 0.4.1

### ISSUE THREAD

**Issue by arnicas** [enjalot/latent-scope#70]
I'm trying to run via a remote vm, and the ls.serve() never loads a valid page-- the console says:

```
index-Y3uMdp44.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
```

There are lots of internet pages about this error... could be as simple as a path string?

**Comment by enjalot** [comment]
are you running from repo or pip installed?

I just looked and I think I fixed a routing bug in 4.2 that might have caused this error
